ORG 2000H             ;STORING THE CANDIDATE AND COUNTER DATA
MVI A,20H
STA 1020H
MVI A,10H
STA 1022H
MVI A,08H
STA 1024H
MVI A,04H
STA 1026H
MVI A,02H
STA 1028H
MVI A,01H
STA 102AH
MVI H,00H
MVI L,00H
SHLD 1030H 
MVI H,00H
MVI L,00H
SHLD 1032H 
MVI H,00H
MVI L,00H
SHLD 1034H  
MVI H,00H
MVI L,00H
SHLD 1036H  
MVI H,00H
MVI L,00H
SHLD 1038H  
MVI H,00H
MVI L,00H
SHLD 103AH 
LOOP:MVI D,01H     ;INPUT FOR THE ELECTION OFFICER
IN 01H
CMP D
JZ START
JNZ OVER
START:IN 02H       ;INPUT FOR THE VOTERS
MVI D,00H
CMP D
JZ START
JNZ LABEL
LABEL:MOV E,A
MVI H,10H
MVI L,20H
MOV A,M
CMP E
LDA 1030H
MOV L,A
LDA 1031H
MOV H,A
CZ INCR
SHLD 1030H
MVI H,10H
MVI L,22H
MOV A,M
CMP E
LDA 1032H
MOV L,A
LDA 1033H
MOV H,A
CZ INCR
SHLD 1032H
MVI H,10H
MVI L,24H
MOV A,M
CMP E
LDA 1034H
MOV L,A
LDA 1035H
MOV H,A
CZ INCR
SHLD 1034H
MVI H,10H
MVI L,26H
MOV A,M
CMP E
LDA 1036H
MOV L,A
LDA 1037H
MOV H,A
CZ INCR
SHLD 1036H
MVI H,10H
MVI L,28H
MOV A,M
CMP E
LDA 1038H
MOV L,A
LDA 1039H
MOV H,A
CZ INCR
SHLD 1038H
MVI H,10H
MVI L,2AH
MOV A,M
CMP E
LDA 103AH
MOV L,A
LDA 103BH
MOV H,A
CZ INCR
SHLD 103AH
JMP LOOP
HLT
INCR:MVI B,00H    ;ADD 0001 TO COUNTER WITH DECIMAL ADJUSTMENT
MVI C,01H
DAD B
MOV A,H
DAA
MOV H,A
MOV A,L
DAA
MOV L,A
RET
OVER:MVI D,02H    ;INPUT FOR CLOSING THE ELECTION PROCESS
CMP D
CZ CLOSE
CNZ LOOP
CLOSE:IN 03H      ;INPUT FOR THE COUNTING OFFICER
CALL INIT          ;LCD INITIALISED
MVI D,03H
CMP D
CNZ CLOSE
CZ NEW
NEW:MVI A,80H
CALL CMD
MVI A,87H
CALL CMD
LXI H,MSG2     ;POINTS TO MSG1
MVI B,0AH       ;SET UP COUNTER FOR 10 CHAR
CALL NEXT
IN 04H    ;FOR DISPLAYING THE CANDIDATE'S COUNTER ON LCD              
MOV E,A
CALL DAT
MVI A,00H
CMP E
JZ NEW
MVI A,09H
CMP E
CZ HALT
MVI A,01H
CMP E
MVI B,10H
MVI C,30H
CZ DISPLAY2
MVI B,0H
MVI C,31H
CZ DISPLAY1
MVI A,02H
CMP E
MVI B,10H
MVI C,32H
CZ DISPLAY2
MVI B,10H
MVI C,33H
CZ DISPLAY1
MVI A,03H
CMP E
MVI B,10H
MVI C,34H
CZ DISPLAY2
MVI B,10H
MVI C,35H
CZ DISPLAY1
MVI A,04H
CMP E
MVI B,10H
MVI C,36H
CZ DISPLAY2
MVI B,10H
MVI C,37H
CZ DISPLAY1
MVI A,05H
CMP E
MVI B,10H
MVI C,38H
CZ DISPLAY2
MVI B,10H
MVI C,39H
CZ DISPLAY1
MVI A,06H
CMP E
MVI B,10H
MVI C,3AH
CZ DISPLAY2
MVI B,10H
MVI C,3BH
CZ DISPLAY1
DISPLAY1:LDAX B
CALL DAT
RET
DISPLAY2:MVI A,C0H
CALL CMD
MVI A,87H
CALL CMD
LXI H,MSG2     ;POINTS TO MSG1
MVI B,08H       ;SET UP COUNTER FOR 8 CHAR
CALL NEXT
LDAX B
CALL DAT
CALL DISPLAY1
JMP NEW
HALT:HLT
INIT:MVI A,80H     ;FOR SETTING PORT A AS OUTPUT
OUT CNTRL            ;8255 CONTROL PORT
MVI A,00H           ;EN signal low
OUT CNTRL
MVI A,30H           ;FOR POWER CODITION FOR LCD
MOV B,A
CALL OUTPUT
CALL CMD
MVI A,38H      ;FOR 8 BIT,2 LINES
CALL CMD
MVI A,08H     ;FOR DISPLAY OFF
CALL CMD
MVI A,01H    ;FOR CLEAR DISPLAY
CALL CMD
MVI A,06H     ;FOR CURSOR INCREASING
CALL CMD
MVI A,0EH      ;FOR DISPLAY,CURSOR AND BLINK
CALL CMD  
CMD:MOV B,A     ;STORE IT IN B
CALL SEVEN
SEVEN:MVI A,90H   ;CHECK THE 7TH PIN
OUT CNTRL
MVI A,02H          ;SELECT COMMAND REGISTER
OUT CNTRL
MVI A,03H
OUT CNTRL
READ:MVI A,01H
OUT CNTRL
IN PORTA         ;READ PORT A AND CHECK 7TH BIT
MVI A,00H       ;SET EN LOW
RLC            
JC READ         ;IF 7TH BIT IS 1,LOOP
MVI A,80H       ;SET PORTA AS OUTPUT PORT
OUT CNTRL
RET
DAT:MOV B,A        ;SAVE IN B
CALL SEVEN         ;CHECK FOR 7TH BIT
MVI A,03H           ;WRITE ENABLE
OUT CNTRL
MVI A,04H        ;SELECT DATA REGISTER
OUT CNTRL
MVI A,01H         ;SET EN
OUT CNTRL
MOV A,B        ;GET DATA BYTE
OUT PORTA
MVI A,00H       ;RESET EN
RET
OUTPUT:MVI A,02H     ;SELECT COMMAND REGISTER
OUT CNTRL
MVI A,04H            ;enable write
OUT CNTRL 
MVI A,01H              ;EN HIGH
OUT CNTRL
MOV A,B               ;GET CODE
OUT PORTA              ;SEND DATA ON BUS
MVI A,00H               ;EN LOW
RET        
NEXT:MOV A,M        ;GET A CHAR
CALL DAT
INX H
DCR B
JNZ NEXT
RET
MSG1:DB "CANDIDATE-"
MSG2:DB "COUNTER-"

